---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: '3.5'

inputs:
- name: repo

outputs:
- name: bin

run:
  path: sh
  args:
  - -exc
  - |
    set
    ls -laR
    echo "done" > bin/log.txt
